### ISSUE TITLE
Blog: Architecture of our Application

### ISSUE THREAD

**Issue by qvalentin** [FileFighter/filefighter.github.io#7]
Hey,
comment your feedback about our "Architecture of our Application" page from your peer-review here:

**Comment by CemYil03** [comment]
Dear FileFighter Team,
I can only agree with the last comment, your blog is really very detailed and looks well.
To me it looks like you just have to implement your well-worked out plan.
On your homepage you say: "Our solution is developed with families in mind".
After reading your blog, it seems to me that your target group is more tech-savvy.
However, I hope you can put your ministry in a easy-to-use application.

Best regards
Cem – FitCom
